/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PetugasEksekusiRouteImport } from './routes/petugas-eksekusi'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as MapRouteImport } from './routes/map'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EditReportRouteImport } from './routes/edit-report'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as DetailReportRouteImport } from './routes/detail-report'
import { Route as CreateReportRouteImport } from './routes/create-report'
import { Route as CompleteReportRouteImport } from './routes/complete-report'
import { Route as AiResultRouteImport } from './routes/ai-result'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasEksekusiRoute = PetugasEksekusiRouteImport.update({
  id: '/petugas-eksekusi',
  path: '/petugas-eksekusi',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EditReportRoute = EditReportRouteImport.update({
  id: '/edit-report',
  path: '/edit-report',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailReportRoute = DetailReportRouteImport.update({
  id: '/detail-report',
  path: '/detail-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReportRoute = CreateReportRouteImport.update({
  id: '/create-report',
  path: '/create-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteReportRoute = CompleteReportRouteImport.update({
  id: '/complete-report',
  path: '/complete-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResultRoute = AiResultRouteImport.update({
  id: '/ai-result',
  path: '/ai-result',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-result': typeof AiResultRoute
  '/complete-report': typeof CompleteReportRoute
  '/create-report': typeof CreateReportRoute
  '/detail-report': typeof DetailReportRoute
  '/drafts': typeof DraftsRoute
  '/edit-report': typeof EditReportRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/my-reports': typeof MyReportsRoute
  '/notifications': typeof NotificationsRoute
  '/petugas-eksekusi': typeof PetugasEksekusiRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/supervisor': typeof SupervisorRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-result': typeof AiResultRoute
  '/complete-report': typeof CompleteReportRoute
  '/create-report': typeof CreateReportRoute
  '/detail-report': typeof DetailReportRoute
  '/drafts': typeof DraftsRoute
  '/edit-report': typeof EditReportRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/my-reports': typeof MyReportsRoute
  '/notifications': typeof NotificationsRoute
  '/petugas-eksekusi': typeof PetugasEksekusiRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/supervisor': typeof SupervisorRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-result': typeof AiResultRoute
  '/complete-report': typeof CompleteReportRoute
  '/create-report': typeof CreateReportRoute
  '/detail-report': typeof DetailReportRoute
  '/drafts': typeof DraftsRoute
  '/edit-report': typeof EditReportRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/my-reports': typeof MyReportsRoute
  '/notifications': typeof NotificationsRoute
  '/petugas-eksekusi': typeof PetugasEksekusiRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/supervisor': typeof SupervisorRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-result'
    | '/complete-report'
    | '/create-report'
    | '/detail-report'
    | '/drafts'
    | '/edit-report'
    | '/home'
    | '/map'
    | '/my-reports'
    | '/notifications'
    | '/petugas-eksekusi'
    | '/reports'
    | '/review'
    | '/stats'
    | '/supervisor'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-result'
    | '/complete-report'
    | '/create-report'
    | '/detail-report'
    | '/drafts'
    | '/edit-report'
    | '/home'
    | '/map'
    | '/my-reports'
    | '/notifications'
    | '/petugas-eksekusi'
    | '/reports'
    | '/review'
    | '/stats'
    | '/supervisor'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/ai-result'
    | '/complete-report'
    | '/create-report'
    | '/detail-report'
    | '/drafts'
    | '/edit-report'
    | '/home'
    | '/map'
    | '/my-reports'
    | '/notifications'
    | '/petugas-eksekusi'
    | '/reports'
    | '/review'
    | '/stats'
    | '/supervisor'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiResultRoute: typeof AiResultRoute
  CompleteReportRoute: typeof CompleteReportRoute
  CreateReportRoute: typeof CreateReportRoute
  DetailReportRoute: typeof DetailReportRoute
  DraftsRoute: typeof DraftsRoute
  EditReportRoute: typeof EditReportRoute
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  MyReportsRoute: typeof MyReportsRoute
  NotificationsRoute: typeof NotificationsRoute
  PetugasEksekusiRoute: typeof PetugasEksekusiRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  StatsRoute: typeof StatsRoute
  SupervisorRoute: typeof SupervisorRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas-eksekusi': {
      id: '/petugas-eksekusi'
      path: '/petugas-eksekusi'
      fullPath: '/petugas-eksekusi'
      preLoaderRoute: typeof PetugasEksekusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-report': {
      id: '/edit-report'
      path: '/edit-report'
      fullPath: '/edit-report'
      preLoaderRoute: typeof EditReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail-report': {
      id: '/detail-report'
      path: '/detail-report'
      fullPath: '/detail-report'
      preLoaderRoute: typeof DetailReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-report': {
      id: '/create-report'
      path: '/create-report'
      fullPath: '/create-report'
      preLoaderRoute: typeof CreateReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-report': {
      id: '/complete-report'
      path: '/complete-report'
      fullPath: '/complete-report'
      preLoaderRoute: typeof CompleteReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-result': {
      id: '/ai-result'
      path: '/ai-result'
      fullPath: '/ai-result'
      preLoaderRoute: typeof AiResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiResultRoute: AiResultRoute,
  CompleteReportRoute: CompleteReportRoute,
  CreateReportRoute: CreateReportRoute,
  DetailReportRoute: DetailReportRoute,
  DraftsRoute: DraftsRoute,
  EditReportRoute: EditReportRoute,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  MyReportsRoute: MyReportsRoute,
  NotificationsRoute: NotificationsRoute,
  PetugasEksekusiRoute: PetugasEksekusiRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  StatsRoute: StatsRoute,
  SupervisorRoute: SupervisorRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
