/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PetugasEksekusiRouteImport } from './routes/petugas-eksekusi'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as MapRouteImport } from './routes/map'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EditReportRouteImport } from './routes/edit-report'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as DetailReportRouteImport } from './routes/detail-report'
import { Route as CreateReportRouteImport } from './routes/create-report'
import { Route as CompleteReportRouteImport } from './routes/complete-report'
import { Route as AiResultRouteImport } from './routes/ai-result'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUprsRouteImport } from './routes/admin/uprs'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminExportRouteImport } from './routes/admin/export'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasEksekusiRoute = PetugasEksekusiRouteImport.update({
  id: '/petugas-eksekusi',
  path: '/petugas-eksekusi',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EditReportRoute = EditReportRouteImport.update({
  id: '/edit-report',
  path: '/edit-report',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailReportRoute = DetailReportRouteImport.update({
  id: '/detail-report',
  path: '/detail-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReportRoute = CreateReportRouteImport.update({
  id: '/create-report',
  path: '/create-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteReportRoute = CompleteReportRouteImport.update({
  id: '/complete-report',
  path: '/complete-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResultRoute = AiResultRouteImport.update({
  id: '/ai-result',
  path: '/ai-result',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUprsRoute = AdminUprsRouteImport.update({
  id: '/admin/uprs',
  path: '/admin/uprs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/admin/export',
  path: '/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-result': typeof AiResultRoute
  '/complete-report': typeof CompleteReportRoute
  '/create-report': typeof CreateReportRoute
  '/detail-report': typeof DetailReportRoute
  '/drafts': typeof DraftsRoute
  '/edit-report': typeof EditReportRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/my-reports': typeof MyReportsRoute
  '/notifications': typeof NotificationsRoute
  '/petugas-eksekusi': typeof PetugasEksekusiRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/supervisor': typeof SupervisorRoute
  '/upload': typeof UploadRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/uprs': typeof AdminUprsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-result': typeof AiResultRoute
  '/complete-report': typeof CompleteReportRoute
  '/create-report': typeof CreateReportRoute
  '/detail-report': typeof DetailReportRoute
  '/drafts': typeof DraftsRoute
  '/edit-report': typeof EditReportRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/my-reports': typeof MyReportsRoute
  '/notifications': typeof NotificationsRoute
  '/petugas-eksekusi': typeof PetugasEksekusiRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/supervisor': typeof SupervisorRoute
  '/upload': typeof UploadRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/uprs': typeof AdminUprsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-result': typeof AiResultRoute
  '/complete-report': typeof CompleteReportRoute
  '/create-report': typeof CreateReportRoute
  '/detail-report': typeof DetailReportRoute
  '/drafts': typeof DraftsRoute
  '/edit-report': typeof EditReportRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/my-reports': typeof MyReportsRoute
  '/notifications': typeof NotificationsRoute
  '/petugas-eksekusi': typeof PetugasEksekusiRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/supervisor': typeof SupervisorRoute
  '/upload': typeof UploadRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/uprs': typeof AdminUprsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-result'
    | '/complete-report'
    | '/create-report'
    | '/detail-report'
    | '/drafts'
    | '/edit-report'
    | '/home'
    | '/map'
    | '/my-reports'
    | '/notifications'
    | '/petugas-eksekusi'
    | '/reports'
    | '/review'
    | '/stats'
    | '/supervisor'
    | '/upload'
    | '/admin/activity'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/uprs'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-result'
    | '/complete-report'
    | '/create-report'
    | '/detail-report'
    | '/drafts'
    | '/edit-report'
    | '/home'
    | '/map'
    | '/my-reports'
    | '/notifications'
    | '/petugas-eksekusi'
    | '/reports'
    | '/review'
    | '/stats'
    | '/supervisor'
    | '/upload'
    | '/admin/activity'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/uprs'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/ai-result'
    | '/complete-report'
    | '/create-report'
    | '/detail-report'
    | '/drafts'
    | '/edit-report'
    | '/home'
    | '/map'
    | '/my-reports'
    | '/notifications'
    | '/petugas-eksekusi'
    | '/reports'
    | '/review'
    | '/stats'
    | '/supervisor'
    | '/upload'
    | '/admin/activity'
    | '/admin/config'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/uprs'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiResultRoute: typeof AiResultRoute
  CompleteReportRoute: typeof CompleteReportRoute
  CreateReportRoute: typeof CreateReportRoute
  DetailReportRoute: typeof DetailReportRoute
  DraftsRoute: typeof DraftsRoute
  EditReportRoute: typeof EditReportRoute
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  MyReportsRoute: typeof MyReportsRoute
  NotificationsRoute: typeof NotificationsRoute
  PetugasEksekusiRoute: typeof PetugasEksekusiRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  StatsRoute: typeof StatsRoute
  SupervisorRoute: typeof SupervisorRoute
  UploadRoute: typeof UploadRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUprsRoute: typeof AdminUprsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas-eksekusi': {
      id: '/petugas-eksekusi'
      path: '/petugas-eksekusi'
      fullPath: '/petugas-eksekusi'
      preLoaderRoute: typeof PetugasEksekusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-report': {
      id: '/edit-report'
      path: '/edit-report'
      fullPath: '/edit-report'
      preLoaderRoute: typeof EditReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail-report': {
      id: '/detail-report'
      path: '/detail-report'
      fullPath: '/detail-report'
      preLoaderRoute: typeof DetailReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-report': {
      id: '/create-report'
      path: '/create-report'
      fullPath: '/create-report'
      preLoaderRoute: typeof CreateReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-report': {
      id: '/complete-report'
      path: '/complete-report'
      fullPath: '/complete-report'
      preLoaderRoute: typeof CompleteReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-result': {
      id: '/ai-result'
      path: '/ai-result'
      fullPath: '/ai-result'
      preLoaderRoute: typeof AiResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uprs': {
      id: '/admin/uprs'
      path: '/admin/uprs'
      fullPath: '/admin/uprs'
      preLoaderRoute: typeof AdminUprsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiResultRoute: AiResultRoute,
  CompleteReportRoute: CompleteReportRoute,
  CreateReportRoute: CreateReportRoute,
  DetailReportRoute: DetailReportRoute,
  DraftsRoute: DraftsRoute,
  EditReportRoute: EditReportRoute,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  MyReportsRoute: MyReportsRoute,
  NotificationsRoute: NotificationsRoute,
  PetugasEksekusiRoute: PetugasEksekusiRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  StatsRoute: StatsRoute,
  SupervisorRoute: SupervisorRoute,
  UploadRoute: UploadRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExportRoute: AdminExportRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUprsRoute: AdminUprsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
