[program:jalankita-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/deltajalan/backend_POSTGRESQL/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ubuntu
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/deltajalan/storage/logs/supervisor-worker.log
stopwaitsecs=3600
